### ISSUE TITLE
timer runs too often

### ISSUE THREAD

**Issue by haraldkoch** [kpcyrd/PKGBUILD-acmetool#1]
You can safely trigger the timer once per *week* ; twice per day is too aggressive, in my opinion.

(love this contribution otherwise!)

**Comment by kpcyrd** [comment]
The timer is the same file [debian is shipping](https://anonscm.debian.org/git/letsencrypt/acmetool.git/tree/debian/acmetool.timer) in their package :)

I'm not sure what their reasoning is, but if a reconcile is not needed, the process quits pretty much instantly.

**Comment by haraldkoch** [comment]
Weird. Okay, ignore me then :)
